import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import './globals.css'





import { Roboto_Flex as Roboto, Bai_Jamjuree as BaiJamjuree, } from "next/font/google";




const roboto = Roboto({ subsets: ['latin'], variable: '--font-roboto' })
const baiJamjuree = BaiJamjuree({
  subsets: ['latin'],
  weight: ['700'],
  variable: '--font-bai-jamjuree',
})



export const metadata: Metadata = {
  title: 'StormGain',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={`${roboto.className}  bg-[#18181b] font-sans text-gray-100`}>{children}</body>
    </html>
  )
}
